<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <KSPBT_ReferenceUnityAssemblies>false</KSPBT_ReferenceUnityAssemblies>
    <KSPBT_ReferenceGameAssemblies>false</KSPBT_ReferenceGameAssemblies>
    <KSPBT_GenerateAssemblyAttribute>false</KSPBT_GenerateAssemblyAttribute>
    <KSPBT_GenerateDependencyAttributes>false</KSPBT_GenerateDependencyAttributes>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Compilation\CompiledObject-doc.md" />
    <None Include="Compilation\KS\kRISC.tpg" />
    <Compile Remove="$(PkgKSPBuildTools)/build/include/Log.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="$(KSPBT_ModRoot)\$(KSPBT_ModPluginFolder)\ICSharpCode.SharpZipLib.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.1.1" GeneratePathProperty="True" />
  </ItemGroup>
</Project>
