<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <ReferenceUnityAssemblies>false</ReferenceUnityAssemblies>
    <ReferenceKSPAssemblies>false</ReferenceKSPAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Compilation\CompiledObject-doc.md" />
    <None Include="Compilation\KS\kRISC.tpg" />
    <Compile Remove="$(PkgKSPBuildTools)/build/include/Log.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="$(RepoRootPath)\$(BinariesOutputRelativePath)\ICSharpCode.SharpZipLib.dll">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="0.0.4" GeneratePathProperty="True" />
  </ItemGroup>
</Project>
