<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <KSPBT_ReferenceUnityAssemblies>false</KSPBT_ReferenceUnityAssemblies>
    <KSPBT_ReferenceGameAssemblies>false</KSPBT_ReferenceGameAssemblies>
    <KSPBT_CopyDLLsToPluginFolder>false</KSPBT_CopyDLLsToPluginFolder>
    <KSPBT_GenerateAssemblyAttribute>false</KSPBT_GenerateAssemblyAttribute>
    <KSPBT_GenerateDependencyAttributes>false</KSPBT_GenerateDependencyAttributes>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Compilation\CompiledObject-doc.md" />
    <None Include="Compilation\KS\kRISC.tpg" />
    <Compile Remove="$(PkgKSPBuildTools)/build/include/Log.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\kOS.Safe\kOS.Safe.csproj">
      <Project>{590FFDA8-7B44-4BC3-A12A-5FFE2BB7D8FD}</Project>
      <Name>kOS.Safe</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="1.8.1.0" />
    <PackageReference Include="NUnit" Version="2.7.1" />
    <PackageReference Include="KSPBuildTools" Version="1.1.1" GeneratePathProperty="True" />
  </ItemGroup>
</Project>
