<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <ReferenceUnityAssemblies>false</ReferenceUnityAssemblies>
    <ReferenceKSPAssemblies>false</ReferenceKSPAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\kOS.Safe\kOS.Safe.csproj">
      <Project>{590FFDA8-7B44-4BC3-A12A-5FFE2BB7D8FD}</Project>
      <Name>kOS.Safe</Name>
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="1.8.1.0" />
    <PackageReference Include="NUnit" Version="2.7.1" />
  </ItemGroup>
</Project>
