<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\kOS.Safe\kOS.Safe.csproj">
      <Project>{590FFDA8-7B44-4BC3-A12A-5FFE2BB7D8FD}</Project>
      <Name>kOS.Safe</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="$(KSPBT_ModRoot)\$(KSPBT_ModPluginFolder)\ICSharpCode.SharpZipLib.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(KSPRoot)\GameData\KSPCommunityPartModules\Plugin\KSPCommunityPartModules.dll">
      <Private>false</Private>
      <CKANIdentifier>KSPCommunityPartModules</CKANIdentifier>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <KSPVersionFile Include=".">
      <Destination>$(KSPBT_ModRoot)/kOS.version</Destination>
      <URL>https://github.com/KSP-KOS/KOS/releases/latest/download/kOS.version</URL>
      <Download>https://github.com/KSP-KOS/KOS/releases/latest</Download>
    </KSPVersionFile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.1.1" />
  </ItemGroup>
</Project>
