name: build

on:
  push:
    branches: [ "develop" ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.props'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.props'
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@0.0.4
    with:
      artifacts: Resources/GameData LICENSE* README* CHANGELOG*
