name: create-release

on:
  workflow_dispatch:
    inputs:
      version-string:
        type: string
        required: true

jobs:
  create-release:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/create-release.yml@release-version-property
    with:
      version-string: ${{ inputs.version-string }}
      version-template-extension:
      version-file: Resources/GameData/kOS/kOS.version
      artifacts: Resources/GameData LICENSE* README* CHANGELOG*

  deploy-docs:
    needs: create-release
    uses: ./.github/workflows/deploy-docs.yml
    with:
      version-string: ${{ inputs.version-string }}
